# -*- coding: utf-8 -*-
"""IronOreMoistureContent(ResNet).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWK-0pBASn8HiJDhzgGzQawjjFQyE_U4
"""

# =====================================================================================
# Moisture Content Recognition Model Integrating Image Texture Features
# Architecture: Dual-Stream ResNet34 + CBAM + MLBP Feature Fusion
# Framework: PyTorch | Target: Google Colab
# =====================================================================================

import os
import sys
import cv2
import zipfile
import shutil
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score

# Graceful Colab detection
try:
    from google.colab import files
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# =====================================================================================
# PART 1: DATASET ARCHITECTURE & PREPROCESSING
# =====================================================================================

ZIP_PATH = "iron_ore_pellets.zip"
BASE_DIR = "dataset_raw"
SPLIT_DIR = "dataset"
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

def generate_mock_dataset(zip_name=ZIP_PATH):
    """Fallback utility to synthesize a dataset if the provided zip is missing."""
    print(f"[WARNING] '{zip_name}' not found. Generating mock dataset to ensure flawless execution...")
    os.makedirs('mock_temp', exist_ok=True)
    with zipfile.ZipFile(zip_name, 'w') as zf:
        for cls in CLASSES:
            os.makedirs(f"mock_temp/{cls}", exist_ok=True)
            # Create 30 images per class for quick mock execution (simulate 500)
            for i in range(30):
                img_path = f"mock_temp/{cls}/img_{i:04d}.jpg"
                # Generate artificial pellets pattern
                img = np.random.randint(50, 150, (224, 224, 3), dtype=np.uint8)
                cv2.circle(img, (112, 112), random.randint(20, 80), (100, 100, 100), -1)
                cv2.imwrite(img_path, img)
                zf.write(img_path, f"{cls}/img_{i:04d}.jpg")
    shutil.rmtree('mock_temp')
    print("[INFO] Mock dataset successfully generated.")

def prepare_dataset_hierarchy():
    """Unzips and enforces splits. Forgiving to case-sensitivity, spaces, and formats."""
    if not os.path.exists(ZIP_PATH):
        generate_mock_dataset()

    print("[INFO] Unzipping dataset programmatically...")
    if os.path.exists(BASE_DIR): shutil.rmtree(BASE_DIR)
    os.makedirs(BASE_DIR)

    with zipfile.ZipFile(ZIP_PATH, 'r') as zip_ref:
        zip_ref.extractall(BASE_DIR)

    all_files = []
    labels = []
    found_folders_with_images = set() # For debugging output

    # Create a normalized mapping dictionary (e.g., '10gm': '10gm')
    # This allows us to match '10GM ' or '10 gm' back to the official '10gm' label
    normalized_classes = {c.lower().replace(" ", ""): c for c in CLASSES}

    for root, dirs, files in os.walk(BASE_DIR):
        parent_folder_raw = os.path.basename(root)
        parent_folder_norm = parent_folder_raw.lower().replace(" ", "")

        # Check for any valid image formats
        img_files = [f for f in files if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif', '.webp'))]

        if len(img_files) > 0:
            found_folders_with_images.add(parent_folder_raw) # Log what we actually found

        if parent_folder_norm in normalized_classes:
            actual_class = normalized_classes[parent_folder_norm]
            valid_files = [os.path.join(root, f) for f in img_files]
            all_files.extend(valid_files)
            labels.extend([actual_class] * len(valid_files))

    # Diagnostic Failsafe
    if len(all_files) == 0:
        print("\n" + "="*60)
        print("[DIAGNOSTIC ERROR] No matching images were found.")
        print("Here are the folders inside your zip file that actually contain images:")
        for fldr in found_folders_with_images:
            print(f" ---> '{fldr}'")
        print("\nThe AI is strictly looking for folders named similar to:", CLASSES)
        print("="*60 + "\n")
        raise ValueError("Dataset mismatch. Please update the 'CLASSES' list at the top of the script to match the folders printed above, or rename the folders inside your zip file.")

    # 70% Train, 30% Temp (Val + Test)
    X_train, X_temp, y_train, y_temp = train_test_split(all_files, labels, test_size=0.30, stratify=labels, random_state=42)
    # 15% Val, 15% Test
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

    print(f"[INFO] Successfully found and mapped {len(all_files)} total images!")
    print("[INFO] Constructing Target Directory Map...")
    if os.path.exists(SPLIT_DIR): shutil.rmtree(SPLIT_DIR)

    for split, paths, lbls in zip(['train', 'val', 'test'], [X_train, X_val, X_test], [y_train, y_val, y_test]):
        for cls in CLASSES:
            os.makedirs(os.path.join(SPLIT_DIR, split, cls), exist_ok=True)
        for path, cls in zip(paths, lbls):
            shutil.copy2(path, os.path.join(SPLIT_DIR, split, cls, os.path.basename(path)))

def print_tree(directory):
    """Visually confirms the structure of the dataset."""
    print(f"\n{directory}/")
    for split in ['train', 'val', 'test']:
        print(f"├── {split}/")
        for i, cls in enumerate(CLASSES):
            connector = "│   └── " if i == len(CLASSES)-1 else "│   ├── "
            file_count = len(os.listdir(os.path.join(directory, split, cls)))
            print(f"{connector}{cls}/ ({file_count} images)")

# Data Augmentation & Normalization
mean_imgnet, std_imgnet = [0.485, 0.456, 0.406], [0.229, 0.224, 0.225]

train_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.ToTensor(),
    transforms.Normalize(mean=mean_imgnet, std=std_imgnet)
])

test_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=mean_imgnet, std=std_imgnet)
])

# =====================================================================================
# PART 2: MATHEMATICAL ALGORITHMS & NETWORK ARCHITECTURE
# =====================================================================================

def compute_mlbp(image_cv_gray):
    """
    Computes Modified Local Binary Pattern (MLBP) over an 8-equidistant neighborhood.
    Preserves structural features against specular highlights by using 3x3 block mean as threshold (tau).
    Output: 256-D normalized histogram vector.
    """
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)

    # Compute threshold tau (mean of 3x3 neighborhood) using convolution
    kernel = np.ones((3, 3), np.float32) / 9.0
    mean_tau = cv2.filter2D(img_float, -1, kernel)

    # Pad image for P=8, R=1 neighbors
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)

    # 8 neighbors defined by offsets
    dx = [-1,  0,  1, 1, 1, 0, -1, -1]
    dy = [-1, -1, -1, 0, 1, 1,  1,  0]

    for i in range(8):
        y1, y2 = 1 + dy[i], 1 + dy[i] + h
        x1, x2 = 1 + dx[i], 1 + dx[i] + w
        neighbor = padded[y1:y2, x1:x2]

        # Step activation: s(x_p - tau)
        bit = (neighbor >= mean_tau).astype(np.uint8)
        mlbp |= (bit << i)

    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    hist = hist.astype(np.float32)
    return hist / (hist.sum() + 1e-6) # L1 Normalization

class PelletDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.root_dir = Path(root_dir)
        self.transform = transform
        self.image_paths = []
        self.labels = []

        # Accept all standard image formats, ignoring uppercase/lowercase differences
        valid_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif', '.webp')

        for idx, cls in enumerate(CLASSES):
            cls_dir = self.root_dir / cls
            if cls_dir.exists():
                for file_name in os.listdir(cls_dir):
                    if file_name.lower().endswith(valid_extensions):
                        self.image_paths.append(str(cls_dir / file_name))
                        self.labels.append(idx)

        if len(self.image_paths) == 0:
            raise ValueError(f"No images found in {root_dir}. Check file formats.")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image_pil = Image.open(img_path).convert('RGB')
        label = self.labels[idx]

        # Global Branch Tensor
        img_tensor = self.transform(image_pil) if self.transform else transforms.ToTensor()(image_pil)

        # MLBP Local Branch Vector
        img_cv_gray = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY)
        img_cv_gray = cv2.resize(img_cv_gray, (224, 224))
        mlbp_vec = compute_mlbp(img_cv_gray)
        mlbp_tensor = torch.tensor(mlbp_vec, dtype=torch.float32)

        return img_tensor, mlbp_tensor, label

class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False),
            nn.ReLU(),
            nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = self.mlp(self.avg_pool(x))
        max_out = self.mlp(self.max_pool(x))
        return self.sigmoid(avg_out + max_out)

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        x_cat = torch.cat([avg_out, max_out], dim=1)
        return self.sigmoid(self.conv(x_cat))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca = ChannelAttention(channels)
        self.sa = SpatialAttention()

    def forward(self, x):
        x = self.ca(x) * x
        x = self.sa(x) * x
        return x

class DualStreamFusionNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        # Backbone (ResNet34 truncated at layer4 -> 512 channels)
        resnet = models.resnet34(weights=models.ResNet34_Weights.IMAGENET1K_V1)
        self.features = nn.Sequential(
            resnet.conv1, resnet.bn1, resnet.relu, resnet.maxpool,
            resnet.layer1, resnet.layer2, resnet.layer3, resnet.layer4
        )
        # Attention
        self.cbam = CBAM(512)
        self.global_pool = nn.AdaptiveAvgPool2d(1)

        # Fusion Classifier (512 Global + 256 Local Texture)
        self.classifier = nn.Sequential(
            nn.Linear(512 + 256, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        # Stream B: Global Branch
        f_global = self.features(img)
        f_global = self.cbam(f_global)
        f_global = self.global_pool(f_global)
        f_global = torch.flatten(f_global, 1) # [B, 512]

        # Multimodal Fusion
        f_fused = torch.cat([f_global, mlbp], dim=1) # [B, 768]

        # Projection
        out = self.classifier(f_fused)
        return out

# =====================================================================================
# PART 3: DEEP LEARNING TRAINING & OPTIMIZATION ENGINE
# =====================================================================================

def train_model():
    prepare_dataset_hierarchy()
    print_tree(SPLIT_DIR)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\n[INFO] Accelerating computation on: {device}")

    train_data = PelletDataset(os.path.join(SPLIT_DIR, 'train'), transform=train_transforms)
    val_data = PelletDataset(os.path.join(SPLIT_DIR, 'val'), transform=test_transforms)

    # Handles dynamic batch sizes for small datasets smoothly
    batch_size = min(32, len(train_data))

    train_loader = DataLoader(train_data, batch_size=batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_data, batch_size=batch_size, shuffle=False, num_workers=2)

    model = DualStreamFusionNet(num_classes=len(CLASSES)).to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-2)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=3)

    epochs = 30
    best_val_loss = float('inf')

    print("\n[INFO] Initializing Dual-Stream Architecture Training...")

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for imgs, mlbps, labels in train_loader:
            imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(imgs, mlbps)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * imgs.size(0)

        train_loss = train_loss / len(train_loader.dataset)

        model.eval()
        val_loss, val_acc = 0.0, 0.0
        all_preds, all_labels = [], []

        with torch.no_grad():
            for imgs, mlbps, labels in val_loader:
                imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
                outputs = model(imgs, mlbps)
                loss = criterion(outputs, labels)
                val_loss += loss.item() * imgs.size(0)

                _, preds = torch.max(outputs, 1)
                all_preds.extend(preds.cpu().numpy())
                all_labels.extend(labels.cpu().numpy())

        val_loss = val_loss / len(val_loader.dataset)
        val_acc = accuracy_score(all_labels, all_preds)
        val_prec = precision_score(all_labels, all_preds, average='macro', zero_division=0)
        val_rec = recall_score(all_labels, all_preds, average='macro', zero_division=0)

        scheduler.step(val_loss)

        print(f"Epoch [{epoch+1}/{epochs}] | Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Acc: {val_acc:.4f} | Prec: {val_prec:.4f} | Rec: {val_rec:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), 'best.pt')

    print("[INFO] Training Complete. Best model saved as 'best.pt'")

    if IN_COLAB:
        try:
            print("[INFO] Initiating automatic download of best weights...")
            files.download('best.pt')
        except Exception as e:
            print(f"[WARNING] Download triggered exception: {e}")

# =====================================================================================
# PART 4: TESTING & VISUAL METRICS PIPELINE
# =====================================================================================

def evaluate_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    test_data = PelletDataset(os.path.join(SPLIT_DIR, 'test'), transform=test_transforms)
    test_loader = DataLoader(test_data, batch_size=32, shuffle=False)

    model = DualStreamFusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best.pt', map_location=device, weights_only=True))
    model.eval()

    all_preds, all_labels = [], []

    print("\n[INFO] Commencing Test Split Evaluation...")
    with torch.no_grad():
        for imgs, mlbps, labels in test_loader:
            imgs, mlbps, labels = imgs.to(device), mlbps.to(device), labels.to(device)
            outputs = model(imgs, mlbps)
            _, preds = torch.max(outputs, 1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    # 1. Classification Report
    print("\n--- Classification Report ---")
    print(classification_report(all_labels, all_preds, target_names=CLASSES, zero_division=0))

    # 2. Confusion Matrix
    cm = confusion_matrix(all_labels, all_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=CLASSES, yticklabels=CLASSES)
    plt.title('Moisture Content Classification - Confusion Matrix')
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.tight_layout()
    plt.show()

    # 3. Inference Verification Test
    print("\n[INFO] Running Single Sample Inference Verification...")
    sample_idx = random.randint(0, len(test_data) - 1)
    img_tensor, mlbp_tensor, label_idx = test_data[sample_idx]

    with torch.no_grad():
        out = model(img_tensor.unsqueeze(0).to(device), mlbp_tensor.unsqueeze(0).to(device))
        _, pred_idx = torch.max(out, 1)

    pred_label = CLASSES[pred_idx.item()]
    true_label = CLASSES[label_idx]

    # De-normalize for visualization
    inv_normalize = transforms.Normalize(
        mean=[-m/s for m, s in zip(mean_imgnet, std_imgnet)],
        std=[1/s for s in std_imgnet]
    )
    img_vis = inv_normalize(img_tensor).permute(1, 2, 0).numpy()
    img_vis = np.clip(img_vis, 0, 1)

    plt.figure(figsize=(4,4))
    plt.imshow(img_vis)
    plt.title(f"True: {true_label} | Predicted: {pred_label}", color='green' if true_label==pred_label else 'red')
    plt.axis('off')
    plt.show()

# =====================================================================================
# MAIN EXECUTION
# =====================================================================================
if __name__ == "__main__":
    train_model()
    evaluate_model()

# =====================================================================================
# INTERACTIVE INFERENCE PIPELINE
# Upload a custom image and get the Moisture Content Prediction
# =====================================================================================

import os
import cv2
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import transforms, models
from google.colab import files
import io

# -------------------------------------------------------------------------
# 1. ARCHITECTURE RECONSTRUCTION (Required to load weights)
# -------------------------------------------------------------------------
CLASSES = ['10gm', '30gm', '40gm', '50gm', '60gm', '70gm', '80gm']

def compute_mlbp(image_cv_gray):
    h, w = image_cv_gray.shape
    img_float = image_cv_gray.astype(np.float32)
    kernel = np.ones((3, 3), np.float32) / 9.0
    mean_tau = cv2.filter2D(img_float, -1, kernel)
    padded = np.pad(img_float, 1, mode='reflect')
    mlbp = np.zeros((h, w), dtype=np.uint8)

    dx = [-1,  0,  1, 1, 1, 0, -1, -1]
    dy = [-1, -1, -1, 0, 1, 1,  1,  0]

    for i in range(8):
        y1, y2 = 1 + dy[i], 1 + dy[i] + h
        x1, x2 = 1 + dx[i], 1 + dx[i] + w
        neighbor = padded[y1:y2, x1:x2]
        bit = (neighbor >= mean_tau).astype(np.uint8)
        mlbp |= (bit << i)

    hist, _ = np.histogram(mlbp.ravel(), bins=256, range=(0, 256))
    hist = hist.astype(np.float32)
    return hist / (hist.sum() + 1e-6)

class ChannelAttention(nn.Module):
    def __init__(self, in_planes, ratio=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.mlp = nn.Sequential(
            nn.Conv2d(in_planes, in_planes // ratio, 1, bias=False),
            nn.ReLU(),
            nn.Conv2d(in_planes // ratio, in_planes, 1, bias=False)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        return self.sigmoid(self.mlp(self.avg_pool(x)) + self.mlp(self.max_pool(x)))

class SpatialAttention(nn.Module):
    def __init__(self, kernel_size=7):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size, padding=kernel_size//2, bias=False)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg_out = torch.mean(x, dim=1, keepdim=True)
        max_out, _ = torch.max(x, dim=1, keepdim=True)
        return self.sigmoid(self.conv(torch.cat([avg_out, max_out], dim=1)))

class CBAM(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.ca = ChannelAttention(channels)
        self.sa = SpatialAttention()

    def forward(self, x):
        x = self.ca(x) * x
        return self.sa(x) * x

class DualStreamFusionNet(nn.Module):
    def __init__(self, num_classes=7):
        super().__init__()
        resnet = models.resnet34()
        self.features = nn.Sequential(
            resnet.conv1, resnet.bn1, resnet.relu, resnet.maxpool,
            resnet.layer1, resnet.layer2, resnet.layer3, resnet.layer4
        )
        self.cbam = CBAM(512)
        self.global_pool = nn.AdaptiveAvgPool2d(1)
        self.classifier = nn.Sequential(
            nn.Linear(512 + 256, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.4),
            nn.Linear(512, num_classes)
        )

    def forward(self, img, mlbp):
        f_global = torch.flatten(self.global_pool(self.cbam(self.features(img))), 1)
        return self.classifier(torch.cat([f_global, mlbp], dim=1))

# -------------------------------------------------------------------------
# 2. INFERENCE & UPLOAD LOGIC
# -------------------------------------------------------------------------
def predict_interactive():
    # Check if weights exist
    if not os.path.exists('best.pt'):
        print("[ERROR] 'best.pt' not found! Please ensure your trained weights file is uploaded to Colab.")
        return

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Loading Model on {device}...")

    # Initialize model and load weights
    model = DualStreamFusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best.pt', map_location=device, weights_only=True))
    model.eval()

    # Preprocessing pipeline
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    print("\n[READY] Please upload an iron ore pellet image for inference.")
    uploaded = files.upload()

    if not uploaded:
        print("[WARNING] No image uploaded.")
        return

    for filename, file_data in uploaded.items():
        try:
            # Load Image
            image_pil = Image.open(io.BytesIO(file_data)).convert('RGB')

            # 1. Global Stream Preparation (ResNet34)
            img_tensor = transform(image_pil).unsqueeze(0).to(device)

            # 2. Local Stream Preparation (MLBP)
            img_cv_gray = cv2.cvtColor(np.array(image_pil), cv2.COLOR_RGB2GRAY)
            img_cv_gray = cv2.resize(img_cv_gray, (224, 224))
            mlbp_vec = compute_mlbp(img_cv_gray)
            mlbp_tensor = torch.tensor(mlbp_vec, dtype=torch.float32).unsqueeze(0).to(device)

            # Inference
            with torch.no_grad():
                outputs = model(img_tensor, mlbp_tensor)
                probabilities = torch.nn.functional.softmax(outputs, dim=1)[0]
                confidence, pred_idx = torch.max(probabilities, 0)

            pred_class = CLASSES[pred_idx.item()]
            conf_score = confidence.item() * 100

            # Visualization
            plt.figure(figsize=(6, 6))
            plt.imshow(image_pil)
            plt.title(f"Prediction: {pred_class} (Confidence: {conf_score:.2f}%)",
                      fontsize=14, color='darkgreen', fontweight='bold')
            plt.axis('off')
            plt.show()

            # Print detailed probabilities for all classes
            print("\n--- Detailed Confidence Scores ---")
            for i, cls_name in enumerate(CLASSES):
                print(f"{cls_name}: {probabilities[i].item() * 100:.2f}%")

        except Exception as e:
            print(f"[ERROR] Failed to process image '{filename}'. Reason: {e}")

# Run the UI
predict_interactive()

# =====================================================================================
# INFERENCE SPEED & FPS BENCHMARKING
# Evaluates latency for real-world mining hardware deployment
# =====================================================================================

import time
import torch
import cv2
import numpy as np
from PIL import Image
from torchvision import transforms

def benchmark_inference(iterations=100):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[INFO] Initializing benchmark on: {device.type.upper()}")

    if not os.path.exists('best.pt'):
        print("[ERROR] 'best.pt' not found! Cannot run benchmark.")
        return

    # 1. Load Model
    model = DualStreamFusionNet(num_classes=len(CLASSES)).to(device)
    model.load_state_dict(torch.load('best.pt', map_location=device, weights_only=True))
    model.eval()

    # 2. Setup standard pipeline transforms
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

    # 3. Create a standardized synthetic image (simulates a camera frame)
    dummy_image = Image.fromarray(np.random.randint(0, 255, (300, 300, 3), dtype=np.uint8))

    # ---------------------------------------------------------
    # HARDWARE WARMUP (Critical for accurate GPU timing)
    # ---------------------------------------------------------
    print("[INFO] Warming up hardware architecture (10 passes)...")
    for _ in range(10):
        i_tensor = transform(dummy_image).unsqueeze(0).to(device)
        i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
        m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)
        with torch.no_grad():
            _ = model(i_tensor, m_tensor)

    print(f"[INFO] Hardware warm-up complete. Benchmarking {iterations} iterations...\n")

    # ---------------------------------------------------------
    # TEST 1: PURE NEURAL NETWORK INFERENCE (GPU Bound)
    # ---------------------------------------------------------
    # Pre-calculate data so we ONLY time the neural network
    img_tensor = transform(dummy_image).unsqueeze(0).to(device)
    img_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
    mlbp_tensor = torch.tensor(compute_mlbp(img_cv), dtype=torch.float32).unsqueeze(0).to(device)

    model_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            _ = model(img_tensor, mlbp_tensor)

            if device.type == 'cuda': torch.cuda.synchronize()
            t_end = time.perf_counter()
            model_times.append((t_end - t_start) * 1000) # Convert to milliseconds

    avg_model_time = np.mean(model_times)

    # ---------------------------------------------------------
    # TEST 2: FULL END-TO-END PIPELINE (CPU + GPU Bound)
    # ---------------------------------------------------------
    pipeline_times = []
    with torch.no_grad():
        for _ in range(iterations):
            if device.type == 'cuda': torch.cuda.synchronize()
            t_start = time.perf_counter()

            # Step A: Data Preprocessing & Local Branch (MLBP Math on CPU)
            i_tensor = transform(dummy_image).unsqueeze(0).to(device)
            i_cv = cv2.resize(cv2.cvtColor(np.array(dummy_image), cv2.COLOR_RGB2GRAY), (224, 224))
            m_tensor = torch.tensor(compute_mlbp(i_cv), dtype=torch.float32).unsqueeze(0).to(device)

            # Step B: Global Branch & Fusion (AI Model on GPU)
            _ = model(i_tensor, m_tensor)

            if device.type == 'cuda': torch.cuda.synchronize()
            t_end = time.perf_counter()
            pipeline_times.append((t_end - t_start) * 1000)

    avg_pipe_time = np.mean(pipeline_times)

    # ---------------------------------------------------------
    # REPORT GENERATION
    # ---------------------------------------------------------
    print("="*60)
    print("                 INFERENCE SPEED REPORT")
    print("="*60)
    print(f"1. Pure AI Model Latency : {avg_model_time:.2f} ms / frame")
    print(f"   Max Theoretical Speed : {1000/avg_model_time:.1f} FPS")
    print("-" * 60)
    print(f"2. Full Pipeline Latency : {avg_pipe_time:.2f} ms / frame")
    print("   (Includes Image Prep + MLBP Math + AI Forward Pass)")
    print(f"   Actual Production FPS : {1000/avg_pipe_time:.1f} FPS")
    print("="*60)
    print("* Note: FPS >= 30 is generally considered real-time for conveyor belt cameras.")

# Execute Benchmark
benchmark_inference()